name: refka
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: fonts/SF-Pro-Display-Semibold.ttf
          weight: 600
        - asset: fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: fonts/SF-Pro-Display-Regular.ttf
          weight: 400
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
